"""
Comprehensive LeetCode problem data for the DSA Roadmap page.
Contains two data structures:
  1. DSA_PATTERNS  - pattern-grouped problems (replaces existing list in server.py ~line 1222)
  2. PROBLEMS_ROADMAP - flat list of 150+ problems sorted by LC number
"""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DSA_PATTERNS  (drop-in replacement for the existing list in server.py)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DSA_PATTERNS = [
    {
        "name": "Two Pointers",
        "description": "Use two pointers to traverse array/string from different positions",
        "problems": [
            {"lc_num": 167, "title": "Two Sum II (Sorted Array)", "difficulty": "Easy", "url": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/"},
            {"lc_num": 15,  "title": "3Sum", "difficulty": "Medium", "url": "https://leetcode.com/problems/3sum/"},
            {"lc_num": 11,  "title": "Container With Most Water", "difficulty": "Medium", "url": "https://leetcode.com/problems/container-with-most-water/"},
            {"lc_num": 42,  "title": "Trapping Rain Water", "difficulty": "Hard", "url": "https://leetcode.com/problems/trapping-rain-water/"},
        ],
    },
    {
        "name": "Sliding Window",
        "description": "Maintain a window over a contiguous subarray/substring",
        "problems": [
            {"lc_num": 643, "title": "Maximum Sum Subarray of Size K", "difficulty": "Easy", "url": "https://leetcode.com/problems/maximum-average-subarray-i/"},
            {"lc_num": 3,   "title": "Longest Substring Without Repeating Characters", "difficulty": "Medium", "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/"},
            {"lc_num": 76,  "title": "Minimum Window Substring", "difficulty": "Hard", "url": "https://leetcode.com/problems/minimum-window-substring/"},
        ],
    },
    {
        "name": "Fast & Slow Pointers",
        "description": "Detect cycles or find middle elements using two-speed traversal",
        "problems": [
            {"lc_num": 141, "title": "Linked List Cycle Detection", "difficulty": "Easy", "url": "https://leetcode.com/problems/linked-list-cycle/"},
            {"lc_num": 876, "title": "Find Middle of Linked List", "difficulty": "Easy", "url": "https://leetcode.com/problems/middle-of-the-linked-list/"},
            {"lc_num": 142, "title": "Linked List Cycle II (Find Start)", "difficulty": "Medium", "url": "https://leetcode.com/problems/linked-list-cycle-ii/"},
        ],
    },
    {
        "name": "BFS / DFS",
        "description": "Breadth-first and depth-first traversal of trees and graphs",
        "problems": [
            {"lc_num": 102, "title": "Binary Tree Level Order Traversal", "difficulty": "Medium", "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/"},
            {"lc_num": 200, "title": "Number of Islands", "difficulty": "Medium", "url": "https://leetcode.com/problems/number-of-islands/"},
            {"lc_num": 127, "title": "Word Ladder", "difficulty": "Hard", "url": "https://leetcode.com/problems/word-ladder/"},
            {"lc_num": 207, "title": "Course Schedule", "difficulty": "Medium", "url": "https://leetcode.com/problems/course-schedule/"},
        ],
    },
    {
        "name": "Binary Search",
        "description": "Search in sorted arrays with modified binary search",
        "problems": [
            {"lc_num": 33,  "title": "Search in Rotated Sorted Array", "difficulty": "Medium", "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
            {"lc_num": 162, "title": "Find Peak Element", "difficulty": "Medium", "url": "https://leetcode.com/problems/find-peak-element/"},
            {"lc_num": 4,   "title": "Median of Two Sorted Arrays", "difficulty": "Hard", "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/"},
        ],
    },
    {
        "name": "Dynamic Programming",
        "description": "Break problems into overlapping subproblems with optimal substructure",
        "problems": [
            {"lc_num": 70,   "title": "Climbing Stairs", "difficulty": "Easy", "url": "https://leetcode.com/problems/climbing-stairs/"},
            {"lc_num": 1143, "title": "Longest Common Subsequence", "difficulty": "Medium", "url": "https://leetcode.com/problems/longest-common-subsequence/"},
            {"lc_num": 416,  "title": "Partition Equal Subset Sum", "difficulty": "Medium", "url": "https://leetcode.com/problems/partition-equal-subset-sum/"},
            {"lc_num": 300,  "title": "Longest Increasing Subsequence", "difficulty": "Medium", "url": "https://leetcode.com/problems/longest-increasing-subsequence/"},
            {"lc_num": 72,   "title": "Edit Distance", "difficulty": "Hard", "url": "https://leetcode.com/problems/edit-distance/"},
        ],
    },
    {
        "name": "Greedy",
        "description": "Make locally optimal choices to find global optimum",
        "problems": [
            {"lc_num": 452,  "title": "Minimum Number of Arrows to Burst Balloons", "difficulty": "Medium", "url": "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/"},
            {"lc_num": 322,  "title": "Coin Change", "difficulty": "Medium", "url": "https://leetcode.com/problems/coin-change/"},
            {"lc_num": 1235, "title": "Maximum Profit in Job Scheduling", "difficulty": "Hard", "url": "https://leetcode.com/problems/maximum-profit-in-job-scheduling/"},
        ],
    },
    {
        "name": "Backtracking",
        "description": "Explore all possibilities by building solutions incrementally",
        "problems": [
            {"lc_num": 51, "title": "N-Queens", "difficulty": "Hard", "url": "https://leetcode.com/problems/n-queens/"},
            {"lc_num": 37, "title": "Sudoku Solver", "difficulty": "Hard", "url": "https://leetcode.com/problems/sudoku-solver/"},
            {"lc_num": 46, "title": "Permutations", "difficulty": "Medium", "url": "https://leetcode.com/problems/permutations/"},
            {"lc_num": 78, "title": "Subsets", "difficulty": "Medium", "url": "https://leetcode.com/problems/subsets/"},
        ],
    },
    {
        "name": "Stack / Monotonic Stack",
        "description": "Use stack for next greater/smaller element patterns",
        "problems": [
            {"lc_num": 20,  "title": "Valid Parentheses", "difficulty": "Easy", "url": "https://leetcode.com/problems/valid-parentheses/"},
            {"lc_num": 496, "title": "Next Greater Element I", "difficulty": "Easy", "url": "https://leetcode.com/problems/next-greater-element-i/"},
            {"lc_num": 84,  "title": "Largest Rectangle in Histogram", "difficulty": "Hard", "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/"},
        ],
    },
    {
        "name": "Hashing",
        "description": "Use hash maps/sets for O(1) lookup-based solutions",
        "problems": [
            {"lc_num": 1,   "title": "Two Sum", "difficulty": "Easy", "url": "https://leetcode.com/problems/two-sum/"},
            {"lc_num": 49,  "title": "Group Anagrams", "difficulty": "Medium", "url": "https://leetcode.com/problems/group-anagrams/"},
            {"lc_num": 128, "title": "Longest Consecutive Sequence", "difficulty": "Medium", "url": "https://leetcode.com/problems/longest-consecutive-sequence/"},
            {"lc_num": 560, "title": "Subarray Sum Equals K", "difficulty": "Medium", "url": "https://leetcode.com/problems/subarray-sum-equals-k/"},
        ],
    },
]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PROBLEMS_ROADMAP  -  flat list of 150+ problems, sorted by lc_num
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROBLEMS_ROADMAP = [
    # --- Arrays ---
    {"lc_num": 1, "name": "Two Sum", "topic": "Arrays", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta", "Apple", "Microsoft", "Flipkart", "Adobe", "Uber", "Intuit", "Paytm", "DE Shaw", "Morgan Stanley"], "url": "https://leetcode.com/problems/two-sum/"},
    {"lc_num": 2, "name": "Add Two Numbers", "topic": "Linked Lists", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Bloomberg", "Adobe", "Morgan Stanley"], "url": "https://leetcode.com/problems/add-two-numbers/"},
    {"lc_num": 3, "name": "Longest Substring Without Repeating Characters", "topic": "Strings", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Flipkart", "Uber", "Intuit", "Apple"], "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/"},
    {"lc_num": 4, "name": "Median of Two Sorted Arrays", "topic": "Binary Search", "difficulty": "Hard", "companies": ["Google", "Amazon", "Apple", "Adobe"], "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/"},
    {"lc_num": 5, "name": "Longest Palindromic Substring", "topic": "Strings", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Meta", "Adobe", "Google"], "url": "https://leetcode.com/problems/longest-palindromic-substring/"},
    {"lc_num": 8, "name": "String to Integer (atoi)", "topic": "Strings", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Meta"], "url": "https://leetcode.com/problems/string-to-integer-atoi/"},
    {"lc_num": 10, "name": "Regular Expression Matching", "topic": "DP", "difficulty": "Hard", "companies": ["Google", "Adobe"], "url": "https://leetcode.com/problems/regular-expression-matching/"},
    {"lc_num": 11, "name": "Container With Most Water", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Flipkart", "Uber", "Apple"], "url": "https://leetcode.com/problems/container-with-most-water/"},
    {"lc_num": 13, "name": "Roman to Integer", "topic": "Strings", "difficulty": "Easy", "companies": ["Microsoft"], "url": "https://leetcode.com/problems/roman-to-integer/"},
    {"lc_num": 14, "name": "Longest Common Prefix", "topic": "Strings", "difficulty": "Easy", "companies": ["Amazon", "Google", "Adobe"], "url": "https://leetcode.com/problems/longest-common-prefix/"},
    {"lc_num": 15, "name": "3Sum", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Meta", "Google", "Flipkart", "Uber", "DE Shaw", "Apple", "Intuit"], "url": "https://leetcode.com/problems/3sum/"},
    {"lc_num": 17, "name": "Letter Combinations of a Phone Number", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Adobe"], "url": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/"},
    {"lc_num": 18, "name": "4Sum", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/4sum/"},
    {"lc_num": 19, "name": "Remove Nth Node From End of List", "topic": "Linked Lists", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft"], "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"},
    {"lc_num": 20, "name": "Valid Parentheses", "topic": "Stack", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Flipkart", "Adobe", "Samsung", "Intuit", "Paytm", "Morgan Stanley", "Apple"], "url": "https://leetcode.com/problems/valid-parentheses/"},
    {"lc_num": 21, "name": "Merge Two Sorted Lists", "topic": "Linked Lists", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Flipkart", "Adobe", "Intuit", "Paytm", "Morgan Stanley"], "url": "https://leetcode.com/problems/merge-two-sorted-lists/"},
    {"lc_num": 22, "name": "Generate Parentheses", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Uber"], "url": "https://leetcode.com/problems/generate-parentheses/"},
    {"lc_num": 23, "name": "Merge k Sorted Lists", "topic": "Linked Lists", "difficulty": "Hard", "companies": ["Amazon", "Meta", "Google", "Microsoft", "Adobe", "Uber"], "url": "https://leetcode.com/problems/merge-k-sorted-lists/"},
    {"lc_num": 25, "name": "Reverse Nodes in k-Group", "topic": "Linked Lists", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/reverse-nodes-in-k-group/"},
    {"lc_num": 28, "name": "Find the Index of the First Occurrence in a String", "topic": "Strings", "difficulty": "Easy", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/"},
    {"lc_num": 33, "name": "Search in Rotated Sorted Array", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft", "Flipkart", "Google"], "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {"lc_num": 34, "name": "Find First and Last Position of Element in Sorted Array", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/"},
    {"lc_num": 37, "name": "Sudoku Solver", "topic": "Backtracking", "difficulty": "Hard", "companies": ["Amazon", "Google", "Microsoft", "Samsung"], "url": "https://leetcode.com/problems/sudoku-solver/"},
    {"lc_num": 39, "name": "Combination Sum", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft", "Samsung"], "url": "https://leetcode.com/problems/combination-sum/"},
    {"lc_num": 40, "name": "Combination Sum II", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/combination-sum-ii/"},
    {"lc_num": 41, "name": "First Missing Positive", "topic": "Arrays", "difficulty": "Hard", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/first-missing-positive/"},
    {"lc_num": 42, "name": "Trapping Rain Water", "topic": "Arrays", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta", "Goldman Sachs", "Flipkart", "Uber", "DE Shaw", "Apple", "Adobe"], "url": "https://leetcode.com/problems/trapping-rain-water/"},
    {"lc_num": 43, "name": "Multiply Strings", "topic": "Strings", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/multiply-strings/"},
    {"lc_num": 45, "name": "Jump Game II", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/jump-game-ii/"},
    {"lc_num": 46, "name": "Permutations", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Meta", "Adobe", "Samsung", "Uber"], "url": "https://leetcode.com/problems/permutations/"},
    {"lc_num": 48, "name": "Rotate Image", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Flipkart", "Adobe", "Samsung", "Morgan Stanley"], "url": "https://leetcode.com/problems/rotate-image/"},
    {"lc_num": 49, "name": "Group Anagrams", "topic": "Hashing", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Flipkart", "Uber", "Intuit", "Morgan Stanley", "Apple"], "url": "https://leetcode.com/problems/group-anagrams/"},
    {"lc_num": 51, "name": "N-Queens", "topic": "Backtracking", "difficulty": "Hard", "companies": ["Google", "Amazon", "Microsoft", "Samsung"], "url": "https://leetcode.com/problems/n-queens/"},
    {"lc_num": 53, "name": "Maximum Subarray", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Apple", "Flipkart", "Adobe", "Uber", "Samsung", "Intuit", "Paytm", "DE Shaw", "Morgan Stanley"], "url": "https://leetcode.com/problems/maximum-subarray/"},
    {"lc_num": 54, "name": "Spiral Matrix", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Flipkart", "Adobe", "Samsung"], "url": "https://leetcode.com/problems/spiral-matrix/"},
    {"lc_num": 55, "name": "Jump Game", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Flipkart", "DE Shaw"], "url": "https://leetcode.com/problems/jump-game/"},
    {"lc_num": 56, "name": "Merge Intervals", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Flipkart", "Uber", "Intuit", "DE Shaw", "Morgan Stanley", "Apple"], "url": "https://leetcode.com/problems/merge-intervals/"},
    {"lc_num": 57, "name": "Insert Interval", "topic": "Arrays", "difficulty": "Medium", "companies": ["Google", "Amazon", "Meta"], "url": "https://leetcode.com/problems/insert-interval/"},
    {"lc_num": 58, "name": "Length of Last Word", "topic": "Strings", "difficulty": "Easy", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/length-of-last-word/"},
    {"lc_num": 62, "name": "Unique Paths", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "DE Shaw"], "url": "https://leetcode.com/problems/unique-paths/"},
    {"lc_num": 64, "name": "Minimum Path Sum", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google", "Goldman Sachs", "DE Shaw"], "url": "https://leetcode.com/problems/minimum-path-sum/"},
    {"lc_num": 70, "name": "Climbing Stairs", "topic": "DP", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Apple", "Flipkart", "Adobe", "Intuit", "Paytm", "Morgan Stanley"], "url": "https://leetcode.com/problems/climbing-stairs/"},
    {"lc_num": 72, "name": "Edit Distance", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Adobe", "DE Shaw"], "url": "https://leetcode.com/problems/edit-distance/"},
    {"lc_num": 73, "name": "Set Matrix Zeroes", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Meta", "Flipkart", "Samsung"], "url": "https://leetcode.com/problems/set-matrix-zeroes/"},
    {"lc_num": 74, "name": "Search a 2D Matrix", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "DE Shaw"], "url": "https://leetcode.com/problems/search-a-2d-matrix/"},
    {"lc_num": 76, "name": "Minimum Window Substring", "topic": "Strings", "difficulty": "Hard", "companies": ["Meta", "Amazon", "Google", "Apple", "Microsoft", "Adobe"], "url": "https://leetcode.com/problems/minimum-window-substring/"},
    {"lc_num": 78, "name": "Subsets", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft", "Adobe", "Samsung", "Uber"], "url": "https://leetcode.com/problems/subsets/"},
    {"lc_num": 79, "name": "Word Search", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Adobe", "Samsung", "Uber"], "url": "https://leetcode.com/problems/word-search/"},
    {"lc_num": 84, "name": "Largest Rectangle in Histogram", "topic": "Stack", "difficulty": "Hard", "companies": ["Amazon", "Google", "Microsoft", "Adobe", "Uber"], "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/"},
    {"lc_num": 88, "name": "Merge Sorted Array", "topic": "Arrays", "difficulty": "Easy", "companies": ["Amazon", "Meta", "Microsoft", "Flipkart", "Adobe", "Paytm"], "url": "https://leetcode.com/problems/merge-sorted-array/"},
    {"lc_num": 91, "name": "Decode Ways", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/decode-ways/"},
    {"lc_num": 94, "name": "Binary Tree Inorder Traversal", "topic": "Trees", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Adobe"], "url": "https://leetcode.com/problems/binary-tree-inorder-traversal/"},
    {"lc_num": 97, "name": "Interleaving String", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/interleaving-string/"},
    {"lc_num": 98, "name": "Validate Binary Search Tree", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft", "Adobe", "Google"], "url": "https://leetcode.com/problems/validate-binary-search-tree/"},
    {"lc_num": 100, "name": "Same Tree", "topic": "Trees", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/same-tree/"},
    {"lc_num": 102, "name": "Binary Tree Level Order Traversal", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft", "Flipkart", "Samsung", "Google"], "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/"},
    {"lc_num": 104, "name": "Maximum Depth of Binary Tree", "topic": "Trees", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Adobe", "Intuit"], "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/"},
    {"lc_num": 105, "name": "Construct Binary Tree from Preorder and Inorder Traversal", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google"], "url": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"},
    {"lc_num": 121, "name": "Best Time to Buy and Sell Stock", "topic": "Arrays", "difficulty": "Easy", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Flipkart", "Intuit", "Paytm", "DE Shaw", "Morgan Stanley", "Apple"], "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
    {"lc_num": 124, "name": "Binary Tree Maximum Path Sum", "topic": "Trees", "difficulty": "Hard", "companies": ["Meta", "Amazon", "Google", "Microsoft", "Adobe", "Uber"], "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/"},
    {"lc_num": 125, "name": "Valid Palindrome", "topic": "Strings", "difficulty": "Easy", "companies": ["Meta", "Amazon", "Microsoft"], "url": "https://leetcode.com/problems/valid-palindrome/"},
    {"lc_num": 127, "name": "Word Ladder", "topic": "Graphs", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta", "Uber", "Adobe"], "url": "https://leetcode.com/problems/word-ladder/"},
    {"lc_num": 128, "name": "Longest Consecutive Sequence", "topic": "Hashing", "difficulty": "Medium", "companies": ["Google", "Amazon", "Meta", "Flipkart", "DE Shaw", "Uber"], "url": "https://leetcode.com/problems/longest-consecutive-sequence/"},
    {"lc_num": 130, "name": "Surrounded Regions", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Samsung"], "url": "https://leetcode.com/problems/surrounded-regions/"},
    {"lc_num": 131, "name": "Palindrome Partitioning", "topic": "Backtracking", "difficulty": "Medium", "companies": ["Amazon", "Google", "Adobe"], "url": "https://leetcode.com/problems/palindrome-partitioning/"},
    {"lc_num": 133, "name": "Clone Graph", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft", "Uber"], "url": "https://leetcode.com/problems/clone-graph/"},
    {"lc_num": 134, "name": "Gas Station", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Google", "Bloomberg"], "url": "https://leetcode.com/problems/gas-station/"},
    {"lc_num": 136, "name": "Single Number", "topic": "Bit Manipulation", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Paytm"], "url": "https://leetcode.com/problems/single-number/"},
    {"lc_num": 138, "name": "Copy List with Random Pointer", "topic": "Linked Lists", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft"], "url": "https://leetcode.com/problems/copy-list-with-random-pointer/"},
    {"lc_num": 139, "name": "Word Break", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google", "Microsoft", "Flipkart", "Adobe", "Uber"], "url": "https://leetcode.com/problems/word-break/"},
    {"lc_num": 140, "name": "Word Break II", "topic": "DP", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/word-break-ii/"},
    {"lc_num": 141, "name": "Linked List Cycle", "topic": "Linked Lists", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Paytm", "Flipkart"], "url": "https://leetcode.com/problems/linked-list-cycle/"},
    {"lc_num": 142, "name": "Linked List Cycle II", "topic": "Linked Lists", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/linked-list-cycle-ii/"},
    {"lc_num": 143, "name": "Reorder List", "topic": "Linked Lists", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft"], "url": "https://leetcode.com/problems/reorder-list/"},
    {"lc_num": 146, "name": "LRU Cache", "topic": "Design", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Meta", "Apple", "Adobe", "Uber", "Flipkart", "Intuit"], "url": "https://leetcode.com/problems/lru-cache/"},
    {"lc_num": 148, "name": "Sort List", "topic": "Linked Lists", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google"], "url": "https://leetcode.com/problems/sort-list/"},
    {"lc_num": 150, "name": "Evaluate Reverse Polish Notation", "topic": "Stack", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/"},
    {"lc_num": 152, "name": "Maximum Product Subarray", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/maximum-product-subarray/"},
    {"lc_num": 153, "name": "Find Minimum in Rotated Sorted Array", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google"], "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    {"lc_num": 155, "name": "Min Stack", "topic": "Stack", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/min-stack/"},
    {"lc_num": 160, "name": "Intersection of Two Linked Lists", "topic": "Linked Lists", "difficulty": "Easy", "companies": ["Amazon", "Meta", "Microsoft"], "url": "https://leetcode.com/problems/intersection-of-two-linked-lists/"},
    {"lc_num": 162, "name": "Find Peak Element", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Google", "Meta", "Microsoft", "DE Shaw"], "url": "https://leetcode.com/problems/find-peak-element/"},
    {"lc_num": 167, "name": "Two Sum II - Input Array Is Sorted", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/"},
    {"lc_num": 169, "name": "Majority Element", "topic": "Arrays", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Paytm", "Flipkart"], "url": "https://leetcode.com/problems/majority-element/"},
    {"lc_num": 189, "name": "Rotate Array", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Paytm"], "url": "https://leetcode.com/problems/rotate-array/"},
    {"lc_num": 190, "name": "Reverse Bits", "topic": "Bit Manipulation", "difficulty": "Easy", "companies": ["Amazon", "Apple", "DE Shaw"], "url": "https://leetcode.com/problems/reverse-bits/"},
    {"lc_num": 191, "name": "Number of 1 Bits", "topic": "Bit Manipulation", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Apple", "DE Shaw"], "url": "https://leetcode.com/problems/number-of-1-bits/"},
    {"lc_num": 198, "name": "House Robber", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Flipkart", "Adobe", "Intuit", "Morgan Stanley"], "url": "https://leetcode.com/problems/house-robber/"},
    {"lc_num": 199, "name": "Binary Tree Right Side View", "topic": "Trees", "difficulty": "Medium", "companies": ["Meta"], "url": "https://leetcode.com/problems/binary-tree-right-side-view/"},
    {"lc_num": 200, "name": "Number of Islands", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Flipkart", "Uber", "Samsung", "Apple"], "url": "https://leetcode.com/problems/number-of-islands/"},
    {"lc_num": 202, "name": "Happy Number", "topic": "Hashing", "difficulty": "Easy", "companies": ["Amazon", "Apple"], "url": "https://leetcode.com/problems/happy-number/"},
    {"lc_num": 206, "name": "Reverse Linked List", "topic": "Linked Lists", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Meta", "Flipkart", "Adobe", "Intuit", "Paytm", "Morgan Stanley"], "url": "https://leetcode.com/problems/reverse-linked-list/"},
    {"lc_num": 207, "name": "Course Schedule", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Flipkart", "Uber", "Samsung", "Adobe"], "url": "https://leetcode.com/problems/course-schedule/"},
    {"lc_num": 209, "name": "Minimum Size Subarray Sum", "topic": "Sliding Window", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google"], "url": "https://leetcode.com/problems/minimum-size-subarray-sum/"},
    {"lc_num": 210, "name": "Course Schedule II", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google", "Adobe"], "url": "https://leetcode.com/problems/course-schedule-ii/"},
    {"lc_num": 213, "name": "House Robber II", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/house-robber-ii/"},
    {"lc_num": 215, "name": "Kth Largest Element in an Array", "topic": "Heap", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google", "Microsoft", "Flipkart", "Uber", "Intuit", "Adobe"], "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/"},
    {"lc_num": 217, "name": "Contains Duplicate", "topic": "Arrays", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Adobe", "Intuit", "Paytm", "Morgan Stanley", "Apple", "Flipkart"], "url": "https://leetcode.com/problems/contains-duplicate/"},
    {"lc_num": 226, "name": "Invert Binary Tree", "topic": "Trees", "difficulty": "Easy", "companies": ["Google", "Amazon", "Microsoft", "Adobe"], "url": "https://leetcode.com/problems/invert-binary-tree/"},
    {"lc_num": 230, "name": "Kth Smallest Element in a BST", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft"], "url": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/"},
    {"lc_num": 235, "name": "Lowest Common Ancestor of a Binary Search Tree", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Microsoft"], "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"},
    {"lc_num": 236, "name": "Lowest Common Ancestor of a Binary Tree", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google", "Microsoft"], "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/"},
    {"lc_num": 238, "name": "Product of Array Except Self", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google", "Microsoft", "Flipkart", "Uber", "Intuit", "DE Shaw", "Morgan Stanley", "Apple"], "url": "https://leetcode.com/problems/product-of-array-except-self/"},
    {"lc_num": 239, "name": "Sliding Window Maximum", "topic": "Sliding Window", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/sliding-window-maximum/"},
    {"lc_num": 242, "name": "Valid Anagram", "topic": "Strings", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Adobe", "Intuit", "Flipkart"], "url": "https://leetcode.com/problems/valid-anagram/"},
    {"lc_num": 253, "name": "Meeting Rooms II", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Uber"], "url": "https://leetcode.com/problems/meeting-rooms-ii/"},
    {"lc_num": 261, "name": "Graph Valid Tree", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"], "url": "https://leetcode.com/problems/graph-valid-tree/"},
    {"lc_num": 268, "name": "Missing Number", "topic": "Bit Manipulation", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Paytm"], "url": "https://leetcode.com/problems/missing-number/"},
    {"lc_num": 269, "name": "Alien Dictionary", "topic": "Graphs", "difficulty": "Hard", "companies": ["Google", "Adobe"], "url": "https://leetcode.com/problems/alien-dictionary/"},
    {"lc_num": 271, "name": "Encode and Decode Strings", "topic": "Strings", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"], "url": "https://leetcode.com/problems/encode-and-decode-strings/"},
    {"lc_num": 283, "name": "Move Zeroes", "topic": "Arrays", "difficulty": "Easy", "companies": ["Microsoft", "Flipkart"], "url": "https://leetcode.com/problems/move-zeroes/"},
    {"lc_num": 287, "name": "Find the Duplicate Number", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/find-the-duplicate-number/"},
    {"lc_num": 295, "name": "Find Median from Data Stream", "topic": "Heap", "difficulty": "Hard", "companies": ["Amazon", "Google", "Meta", "Microsoft", "Uber", "Adobe"], "url": "https://leetcode.com/problems/find-median-from-data-stream/"},
    {"lc_num": 297, "name": "Serialize and Deserialize Binary Tree", "topic": "Trees", "difficulty": "Hard", "companies": ["Amazon", "Meta", "Google", "Microsoft", "Uber", "Adobe"], "url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"},
    {"lc_num": 300, "name": "Longest Increasing Subsequence", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Adobe", "Samsung", "DE Shaw", "Morgan Stanley"], "url": "https://leetcode.com/problems/longest-increasing-subsequence/"},
    {"lc_num": 312, "name": "Burst Balloons", "topic": "DP", "difficulty": "Hard", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/burst-balloons/"},
    {"lc_num": 315, "name": "Count of Smaller Numbers After Self", "topic": "Arrays", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/count-of-smaller-numbers-after-self/"},
    {"lc_num": 322, "name": "Coin Change", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Flipkart", "Adobe", "Intuit", "DE Shaw", "Morgan Stanley"], "url": "https://leetcode.com/problems/coin-change/"},
    {"lc_num": 323, "name": "Number of Connected Components in an Undirected Graph", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"], "url": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/"},
    {"lc_num": 338, "name": "Counting Bits", "topic": "Bit Manipulation", "difficulty": "Easy", "companies": ["Amazon", "Google", "DE Shaw"], "url": "https://leetcode.com/problems/counting-bits/"},
    {"lc_num": 344, "name": "Reverse String", "topic": "Strings", "difficulty": "Easy", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/reverse-string/"},
    {"lc_num": 347, "name": "Top K Frequent Elements", "topic": "Heap", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Flipkart", "Uber"], "url": "https://leetcode.com/problems/top-k-frequent-elements/"},
    {"lc_num": 355, "name": "Design Twitter", "topic": "Heap", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/design-twitter/"},
    {"lc_num": 371, "name": "Sum of Two Integers", "topic": "Bit Manipulation", "difficulty": "Medium", "companies": ["Amazon", "Google", "DE Shaw"], "url": "https://leetcode.com/problems/sum-of-two-integers/"},
    {"lc_num": 373, "name": "Find K Pairs with Smallest Sums", "topic": "Heap", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/"},
    {"lc_num": 377, "name": "Combination Sum IV", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/combination-sum-iv/"},
    {"lc_num": 380, "name": "Insert Delete GetRandom O(1)", "topic": "Design", "difficulty": "Medium", "companies": ["Uber"], "url": "https://leetcode.com/problems/insert-delete-getrandom-o1/"},
    {"lc_num": 387, "name": "First Unique Character in a String", "topic": "Strings", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Paytm"], "url": "https://leetcode.com/problems/first-unique-character-in-a-string/"},
    {"lc_num": 416, "name": "Partition Equal Subset Sum", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/partition-equal-subset-sum/"},
    {"lc_num": 417, "name": "Pacific Atlantic Water Flow", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Samsung"], "url": "https://leetcode.com/problems/pacific-atlantic-water-flow/"},
    {"lc_num": 424, "name": "Longest Repeating Character Replacement", "topic": "Sliding Window", "difficulty": "Medium", "companies": ["Google", "Amazon"], "url": "https://leetcode.com/problems/longest-repeating-character-replacement/"},
    {"lc_num": 427, "name": "Construct Quad Tree", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/construct-quad-tree/"},
    {"lc_num": 435, "name": "Non-overlapping Intervals", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google"], "url": "https://leetcode.com/problems/non-overlapping-intervals/"},
    {"lc_num": 438, "name": "Find All Anagrams in a String", "topic": "Sliding Window", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/find-all-anagrams-in-a-string/"},
    {"lc_num": 452, "name": "Minimum Number of Arrows to Burst Balloons", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Meta"], "url": "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/"},
    {"lc_num": 460, "name": "LFU Cache", "topic": "Design", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/lfu-cache/"},
    {"lc_num": 480, "name": "Sliding Window Median", "topic": "Heap", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/sliding-window-median/"},
    {"lc_num": 494, "name": "Target Sum", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/target-sum/"},
    {"lc_num": 496, "name": "Next Greater Element I", "topic": "Stack", "difficulty": "Easy", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/next-greater-element-i/"},
    {"lc_num": 518, "name": "Coin Change II", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/coin-change-ii/"},
    {"lc_num": 543, "name": "Diameter of Binary Tree", "topic": "Trees", "difficulty": "Easy", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/diameter-of-binary-tree/"},
    {"lc_num": 547, "name": "Number of Provinces", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Microsoft", "Google", "Samsung"], "url": "https://leetcode.com/problems/number-of-provinces/"},
    {"lc_num": 560, "name": "Subarray Sum Equals K", "topic": "Hashing", "difficulty": "Medium", "companies": ["Meta", "Amazon", "Google", "Flipkart", "Microsoft", "Uber"], "url": "https://leetcode.com/problems/subarray-sum-equals-k/"},
    {"lc_num": 567, "name": "Permutation in String", "topic": "Sliding Window", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/permutation-in-string/"},
    {"lc_num": 572, "name": "Subtree of Another Tree", "topic": "Trees", "difficulty": "Easy", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/subtree-of-another-tree/"},
    {"lc_num": 621, "name": "Task Scheduler", "topic": "Greedy", "difficulty": "Medium", "companies": ["Meta", "Amazon", "Google", "Uber"], "url": "https://leetcode.com/problems/task-scheduler/"},
    {"lc_num": 632, "name": "Smallest Range Covering Elements from K Lists", "topic": "Heap", "difficulty": "Hard", "companies": ["Adobe"], "url": "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/"},
    {"lc_num": 647, "name": "Palindromic Substrings", "topic": "Strings", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google"], "url": "https://leetcode.com/problems/palindromic-substrings/"},
    {"lc_num": 678, "name": "Valid Parenthesis String", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/valid-parenthesis-string/"},
    {"lc_num": 684, "name": "Redundant Connection", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/redundant-connection/"},
    {"lc_num": 703, "name": "Kth Largest Element in a Stream", "topic": "Heap", "difficulty": "Easy", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/kth-largest-element-in-a-stream/"},
    {"lc_num": 704, "name": "Binary Search", "topic": "Binary Search", "difficulty": "Easy", "companies": ["Amazon", "Microsoft", "Google", "Adobe", "Intuit", "Morgan Stanley"], "url": "https://leetcode.com/problems/binary-search/"},
    {"lc_num": 721, "name": "Accounts Merge", "topic": "Graphs", "difficulty": "Medium", "companies": ["Uber"], "url": "https://leetcode.com/problems/accounts-merge/"},
    {"lc_num": 733, "name": "Flood Fill", "topic": "Graphs", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft", "Samsung"], "url": "https://leetcode.com/problems/flood-fill/"},
    {"lc_num": 739, "name": "Daily Temperatures", "topic": "Stack", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"], "url": "https://leetcode.com/problems/daily-temperatures/"},
    {"lc_num": 743, "name": "Network Delay Time", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Uber"], "url": "https://leetcode.com/problems/network-delay-time/"},
    {"lc_num": 763, "name": "Partition Labels", "topic": "Greedy", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/partition-labels/"},
    {"lc_num": 767, "name": "Reorganize String", "topic": "Heap", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"], "url": "https://leetcode.com/problems/reorganize-string/"},
    {"lc_num": 787, "name": "Cheapest Flights Within K Stops", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta", "Uber"], "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/"},
    {"lc_num": 875, "name": "Koko Eating Bananas", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/koko-eating-bananas/"},
    {"lc_num": 876, "name": "Middle of the Linked List", "topic": "Linked Lists", "difficulty": "Easy", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/middle-of-the-linked-list/"},
    {"lc_num": 895, "name": "Maximum Frequency Stack", "topic": "Stack", "difficulty": "Hard", "companies": ["Amazon", "Google", "Adobe"], "url": "https://leetcode.com/problems/maximum-frequency-stack/"},
    {"lc_num": 912, "name": "Sort an Array", "topic": "Arrays", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/sort-an-array/"},
    {"lc_num": 973, "name": "K Closest Points to Origin", "topic": "Heap", "difficulty": "Medium", "companies": ["Amazon", "Meta", "Google", "Uber"], "url": "https://leetcode.com/problems/k-closest-points-to-origin/"},
    {"lc_num": 981, "name": "Time Based Key-Value Store", "topic": "Binary Search", "difficulty": "Medium", "companies": ["Amazon", "Google", "Meta"], "url": "https://leetcode.com/problems/time-based-key-value-store/"},
    {"lc_num": 994, "name": "Rotting Oranges", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Uber", "Samsung"], "url": "https://leetcode.com/problems/rotting-oranges/"},
    {"lc_num": 1046, "name": "Last Stone Weight", "topic": "Heap", "difficulty": "Easy", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/last-stone-weight/"},
    {"lc_num": 1143, "name": "Longest Common Subsequence", "topic": "DP", "difficulty": "Medium", "companies": ["Amazon", "Google", "Microsoft", "Morgan Stanley"], "url": "https://leetcode.com/problems/longest-common-subsequence/"},
    {"lc_num": 1235, "name": "Maximum Profit in Job Scheduling", "topic": "DP", "difficulty": "Hard", "companies": ["Amazon", "Google", "Microsoft"], "url": "https://leetcode.com/problems/maximum-profit-in-job-scheduling/"},
    {"lc_num": 1448, "name": "Count Good Nodes in Binary Tree", "topic": "Trees", "difficulty": "Medium", "companies": ["Amazon", "Microsoft"], "url": "https://leetcode.com/problems/count-good-nodes-in-binary-tree/"},
    {"lc_num": 1584, "name": "Min Cost to Connect All Points", "topic": "Graphs", "difficulty": "Medium", "companies": ["Amazon", "Google"], "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/"},
    {"lc_num": 2013, "name": "Detect Squares", "topic": "Hashing", "difficulty": "Medium", "companies": ["Google", "Amazon"], "url": "https://leetcode.com/problems/detect-squares/"},
]
